### ISSUE TITLE
notification 2 (fix backend)

### ISSUE THREAD

**Issue by cch5ng** [cch5ng/wastenot#64]
1 fix backend; implement actual notification check

* logic for saving notification dates/data to a new notification table

* logic for scheduling when to get notification lists

2 refactor backend + frontend

replace the test logic and hookup to the actual logic which should trigger the push message

3 also fix some notification details (look at topics related to push message UX, notification visual options, need to also define close notification behavior?)

FE

   * Settings > testBtnClickHandler() and Button with label: "Test Push Message" => all should go away

   * http_requests > Auth.testPushSubscription() => this should just go away

BE

   * Auth endpoint post '/testPush'; most of the logic should be re-used but think probably it is not going to be triggered through the endpoint; probably the scheduled job should just trigger helper function

------

https://alligator.io/nodejs/node-cron/

**Comment by cch5ng** [comment]
* may have fixed the issue with saving new shopping list (all list items getting saved properly when mapping test was saved in form add mode)

**Comment by cch5ng** [comment]
042720 one issue when constructing notify_timestamp is that one component, expirationMs, is string but expected to be a num

**Comment by cch5ng** [comment]
042820

```
UnhandledPromiseRejectionWarning: ReferenceError: next is not defined
    at /Users/cchung/programming/projects/wastenot/server/app/utils/notification_scheduler.js:33:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:34870) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```
