### ISSUE TITLE
update db requests

### ISSUE THREAD

**Issue by cch5ng** [cch5ng/wastenot#81]
per latest version of pg (8.x)

- [x] update pool config for max connections
- [x] go through each BE request and make sure db returns results/err
- [x] fix return for correct status codes (200, 201, 204, 401, 404)
- [x] fix return some kind of human friendly message (at least clear success vs error/fix)

**Comment by cch5ng** [comment]
record of changes made

* test all requests

   * X-(fixed) failing POST http://localhost:3000/api/list/shoppingLists/add

      * looks like something gets saved: the high level list gets saved but the list items do not appear to get saved (only first item, not any of the latter)

```
databasePool.js:28
      console.log('executed query', { text, duration, rows: res.rowCount })
                                                                ^

TypeError: Cannot read property 'rowCount' of undefined
    at /Users/carolchung/programming/projects/wastenot/server/databasePool.js:28:65
    at Object.callback (/Users/carolchung/programming/projects/wastenot/server/node_modules/pg-pool/index.js:345:16)

```

   * also when I click to open the create shopping list form, see this request just hanging http://localhost:3000/api/listItemMap/ (this is before performing the categories mapping test)

   * (X-fixed) failing POST http://localhost:3000/api/listItemMap/

   * (X-fixed) failing POST http://localhost:3000/api/list/shoppingLists/add

   * (X-fixed) failing POST http://localhost:3000/api/list/templateLists/add

      * not sure if setting init notify timestamp to null is correct

      * think there is missing timestamp param value in the inside function call

```
list/table.js:19
                return ListItemTable.storeListItem({ name, list_guid, list_item_guid, sortOrder, timestamp, notify_timestamp })
                                                                                                 ^

ReferenceError: timestamp is not defined
    at /Users/carolchung/programming/projects/wastenot/server/app/list/table.js:19:98
```

   * (X-fixed) failing retrieve template list by id (the id is not appearing in the request); http://localhost:3000/api/list/listDetail/undefined

   * passing POST http://localhost:3000/api/list/listDetail/

      * getting back results but the view goes blank

```
ShoppingListDetailForm.js:268 Uncaught (in promise) TypeError: Cannot read property 'checked' of undefined
    at renderForm (ShoppingListDetailForm.js:268)
    at ShoppingListFormNoExpiration (ShoppingListFormNoExpiration.js:48)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at beginWork (react-dom.development.js:18610)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
```

   * passing PUT http://localhost:3000/api/auth/settings/timezone

      * not sure why it is PUT vs POST but should update the return status code and verify this is a correct request

   * passing POST http://localhost:3000/api/list/templateLists

      * effectively getting user's list of templates

   * passing POST http://localhost:3000/api/list/shoppingLists

      * effectively getting user's list of shopping lists

   * passing POST http://localhost:3000/api/setting/listItemMapping

      * gets whether the person completed their categories mapping or not

   * (X-fixed) hanging on POST http://localhost:3000/api/list/listDetail/:id

      * gets called when click on specific list to edit

   * (X-fixed) hanging on POST http://localhost:3000/api/list/notifications

   * hanging on POST http://localhost:3000/api/listItemMap/

   * this works, POST http://localhost:3000/api/listItemMap/add

      * but it should return a success/error message and also should redirect to probably the default view (?)

**Comment by cch5ng** [comment]
bug: trying to click to edit a template list; think the issue is that the last item in the list was added directly to app store (not coming from a http get refresh) so the list id is missing and the request for indiv list fails
