### ISSUE TITLE
alerts (push notifications) do not display

### ISSUE THREAD

**Issue by cch5ng** [cch5ng/wastenot#97]
sw gets registered and logic for checking permissions works; not sure where the breakage is occurring yet

also would like to follow up on the issue with handling click on react select comp (new shopping list form); do some kind of error validation on FE (if cannot get some data needed to save, show the error on the FE before making the request; otherwise show the error on FE if the BE returned some error on trying to save)

------

looks like in sw, logic is getting through to askPermission() at least

but most likely failing in subscribeUserToPush() or afterward

**Comment by cch5ng** [comment]
error running from notification_scheduler.js

```
error Error: No subject set in vapidDetails.subject.
    at Object.validateSubject (/Users/carolchung/programming/projects/wastenot/server/node_modules/web-push/src/vapid-helper.js:70:11)
    at Object.WebPushLib.setVapidDetails (/Users/carolchung/programming/projects/wastenot/server/node_modules/web-push/src/web-push-lib.js:59:17)
    at triggerPushMsg (/Users/carolchung/programming/projects/wastenot/server/app/utils/pushMessage.js:11:13)
    at /Users/carolchung/programming/projects/wastenot/server/app/utils/notification_scheduler.js:79:45
    at Array.forEach (<anonymous>)
    at /Users/carolchung/programming/projects/wastenot/server/app/utils/notification_scheduler.js:74:74
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by cch5ng** [comment]
updated vapid keys and config

had to enable sections of service worker and manually run additional server script (documented in wiki: 000 topic)
